pipeline {
    agent {
        label ' ubuntu '
    }
    stages {
        stage('Build') { 
            steps {
                sh 'pip3 install -r requirement.txt'
            }
        }
        stage('Test') { 
            steps {
                sh 'python3 manage.py test'
            }
        }
        stage('Deploy') { 
            steps {
             sh "echo"
               
            
           
               

    
            }
        }
    }
}
